name: build-riki-stable
on:
  merge_group:
  pull_request:
    branches:
      - main
      - testing
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
  schedule:
    - cron: '41 15 * * 2'  # 15:41 UTC every Tuesday
  workflow_dispatch:

jobs:
  build:
    name: build
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      brand_name: riki
      stream_name: stable